---
all:
  hosts:
    server1:
      ansible_host: 192.168.1.101

  children:
    proxmox_hosts:
      hosts:
        node_01:
          ansible_host: 
        node_02:
          ansible_host:


    bare_metal_linux:
      hosts:
        alma_01:
          ansible_host:

    windows_vms:
      hosts:
        bf3_01:
          ansible_host:

    linux_vms:
      hosts:

